# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2771c4eb686de1d7c534b614e392c41c958985c3ddd36450472bdd3958a094f0876be1c145d95274ec7a1fb3f9e2fb43121527db139c885f073474fb1bf5ede5



test:
  secret_key_base: 1b0a6d51d1deb7e6303a95ea535003f1f2c5cb3ca057ccc861c59e51e10492e6a4622b37e670903db537be1b8107f5c976001469e62412e69790109ab24366f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mail_username: <%= ENV["MAIL_USERNAME"] %>




